[package]
name = "seed-scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
batbox-la = "0.16.0"
clap = { version = "4.5.41", features = ["derive"] }
image = { version = "0.25.6", default-features = false, features = ["png"] }
